# Generated by Django 4.2.6 on 2023-10-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("info", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentalConsole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("console", models.CharField(verbose_name="Game console")),
                ("game", models.CharField(verbose_name="Game")),
                ("number", models.CharField(verbose_name="phone number")),
                ("address", models.CharField(verbose_name="delivery address")),
                ("delivery_date", models.DateField(verbose_name="delivery date")),
                ("delivery_time", models.TimeField(verbose_name="delivery time")),
            ],
        ),
    ]
